### ISSUE TITLE
Update TAGADA name, link to github and version in the MultiQC report?

### ISSUE THREAD

**Issue by syfobfx** [FAANG/proj-gs-rna-seq#3]
The MultiQC report page starts by: 

> **This report was generated by the Gene-SWitCH RNA-Seq analysis pipeline.**

with an outdated link "https://github.com/FAANG/proj-gs-rna-seq"

Is it possible to update the link (to "https://github.com/FAANG/analysis-TAGADA") and the name of the pipeline, and if possible add the version number too?
This would give for instance: 

> **This report was generated by the RNA-Seq data analysis pipeline TAGADA v1.0.2.**

Thanks!

**Comment by chbk** [comment]
Thanks for your suggestion @syfobfx, we will change that in the upcoming release.
