### ISSUE TITLE
TAGADA_control_annotation -no reference transcripts in the TPM files

### ISSUE THREAD

**Issue by G-Thomson** [FAANG/proj-gs-rna-seq#7]
Hi

I am trying to use TAGADA to improve my annotation of a plant genome. 
I input my draft annotation as a GTF file (v 2.2) and provided 40 BAM files of RNA-Seq I had previously aligned with HiSat2. 
I am using the Singularity profile.

This is the error I get:
```
ERROR ~ Error executing process > 'TAGADA_control_annotation (1)'

Caused by:
  Process `TAGADA_control_annotation (1)` terminated with an error exit status (2)
```

`awk: cmd. line:1: fatal: division by zero attempted`

I had a look at the code and working directory, and the process is using bash scripts from here: https://github.com/sdjebali/Scripts

I notice that the `detected_transcripts_genes_numbers.tsv` file created by `compute_detected_tr_gn.sh` script lists no reference transcripts in the TPM files. 
 
```
column -t detected_transcripts_genes_numbers.tsv
Element     ref_nb  ref_in_file_nb  ref_in_file_pcent  ref_det_nb  ref_det_pcent  nov_nb  nov_det_nb  nov_det_pcent
transcript  68618   0               0                  0           0              425258  316561      74.4398
gene        68131   0               0                  0           0              122994  74996       60.9753
```

Thus when `ref_pred_all_expr_2_tr_ratio_size_pos.sh` is called there is nothing written to `ref.annot.tpm0.1.2samples.exons.gff`.
I think this is what is causing things to fail. However the lack of reference transcripts in the TPM files makes me think something went wrong further upstream of this process.

Are you able to help me?
Should I go back to the beginning and use raw FASTQ files?

Looking into the working directory I see this:
```
tree
.
├── detected_transcripts_genes_numbers.tsv
├── novel_genes_TPM.tsv -> ... /TAGADA/tmp_TAGADAWorkdir/90/e2efb9408bde132d1f8e7a0e6e91f3/novel_genes_TPM.tsv
├── novel.gtf -> .../TAGADA/tmp_TAGADAWorkdir/96/c6b49e78f0dc192caaaea25815cc69/novel.gtf
├── novel_transcripts_TPM.tsv -> ... /TAGADA/tmp_TAGADAWorkdir/ad/7388e9888b64836065fdd67c216283/novel_transcripts_TPM.tsv
├── OverlapsClassesACE_sorted.gtf -> ... /OverlapsClassesACE_sorted.gtf
├── ref
│   ├── analyse_transcript_models_ref.err
│   ├── distinct_exon_length_OverlapsClassesACE_sorted.txt
│   ├── distinct_internal_exon_length_OverlapsClassesACE_sorted.txt
│   ├── exon_length_OverlapsClassesACE_sorted.txt
│   ├── gn_3p_exon_OverlapsClassesACE_sorted_length.txt
│   ├── gn_5p_exon_OverlapsClassesACE_sorted_length.txt
│   ├── internal_exons_OverlapsClassesACE_sorted_length.txt
│   ├── make_summary_stat_from_annot_OverlapsClassesACE_sorted.out
│   ├── monoextr_exons_OverlapsClassesACE_sorted_length.txt
│   ├── OverlapsClassesACE_sorted_capped_sites.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr_with_annottss_less100bp.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr_with_annottss_less500bp.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr_with_annottss_less50bp.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr_with_pred_less100bp.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr_with_pred_less500bp.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr_with_pred_less50bp.gff
│   ├── OverlapsClassesACE_sorted_complete_complete.gff
│   ├── OverlapsClassesACE_sorted_complete_comp_refinedclass_nbex_intermclass.tsv
│   ├── OverlapsClassesACE_sorted_complete_gnid_nbtr.txt
│   ├── OverlapsClassesACE_sorted_complete_trid_nbex.txt
│   ├── OverlapsClassesACE_sorted_gnid_nbtr.txt
│   ├── OverlapsClassesACE_sorted.gtf
│   ├── OverlapsClassesACE_sorted_predtr_spliced_stranded_exact_OverlapsClassesACE_sorted_correstrlist_TSS_AnnotTSSlist_TTS_AnnotTTSlist_smallerdist_TSS_TTS.txt
│   ├── OverlapsClassesACE_sorted_predtr_spliced_stranded_exact_OverlapsClassesACE_sorted_correstrlist_TSS_AnnotTSSlist_TTS_AnnotTTSlist.txt
│   ├── OverlapsClassesACE_sorted_trid_nbex.txt
│   ├── OverlapsClassesACE_sorted_tts_sites.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr_with_annottts_less100bp.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr_with_annottts_less500bp.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr_with_annottts_less50bp.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr_with_pred_less100bp.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr_with_pred_less500bp.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr_with_pred_less50bp.gff
│   ├── prediction_sumstat.txt
│   ├── tr_3p_exon_OverlapsClassesACE_sorted_length.txt
│   ├── tr_5p_exon_OverlapsClassesACE_sorted_length.txt
│   ├── tr_cumulexlg_OverlapsClassesACE_sorted.txt
│   └── tr_lgwithexintr_OverlapsClassesACE_sorted.txt
├── ref.annot.tpm0.1.2samples.exons.gff
├── ref_expr
│   ├── analyse_transcript_models_ref_expr.err
│   ├── make_summary_stat_from_annot_ref.annot.tpm0.1.2samples.exons.out
│   ├── OverlapsClassesACE_sorted_capped_sites.gff
│   ├── OverlapsClassesACE_sorted_capped_sites_nr.gff
│   ├── OverlapsClassesACE_sorted.gtf
│   ├── OverlapsClassesACE_sorted_tts_sites.gff
│   ├── OverlapsClassesACE_sorted_tts_sites_nr.gff
│   ├── ref.annot.tpm0.1.2samples.exons_distinct_exons.txt
│   ├── ref.annot.tpm0.1.2samples.exons_distinct_introns_bed.txt
│   ├── ref.annot.tpm0.1.2samples.exons_distinct_introns_minus1nteachside.txt
│   ├── ref.annot.tpm0.1.2samples.exons_distinct_introns.txt
│   ├── ref.annot.tpm0.1.2samples.exons_exons_sorted_by_tr.gff
│   ├── ref.annot.tpm0.1.2samples.exons_genes.gff
│   ├── ref.annot.tpm0.1.2samples.exons.gff
│   ├── ref.annot.tpm0.1.2samples.exons_gnid_nbtr.txt
│   ├── ref.annot.tpm0.1.2samples.exons_gnids.txt
│   ├── ref.annot.tpm0.1.2samples.exons_introns.gff
│   ├── ref.annot.tpm0.1.2samples.exons_transcripts.gff
│   ├── ref.annot.tpm0.1.2samples.exons_trid_nbex.txt
│   └── ref.annot.tpm0.1.2samples.exons_trids.txt
├── ref_gn_id.txt
├── ref_tr_id.txt
├── string
│   ├── novel.gtf
│   └── OverlapsClassesACE_sorted.gtf
├── string_expr
│   ├── OverlapsClassesACE_sorted.gtf
│   └── stringtie.annot.tpm0.1.2samples.exons.gff
└── stringtie.annot.tpm0.1.2samples.exons.gff
```

**Comment by sdjebali** [comment]
Thanks for using TAGADA.

Would it be possible for you to share the full content of the TAGADA_control_annotation process directory ?

it would be very helpful to us to investigate why it does not count any reference transcript ?

Otherwise just the initial reference annotation gff file ?

Best,

**Comment by G-Thomson** [comment]
Hi Sarah

Thanks for your help.

Here is the initial reference annotation gff file:

[OverlapsClassesACE_sorted.gtf.gz](https://github.com/FAANG/analysis-TAGADA/files/15203652/OverlapsClassesACE_sorted.gtf.gz)

and I have put the TAGADA_control_annotation process directory which you should be able to access.

https://drive.google.com/drive/folders/1lrZ8ykmSIVobilGblAoquKAevMd-Wmk9?usp=sharing

Cheers

Geoffrey

**Comment by G-Thomson** [comment]
Maybe its because most of my input annotation's don't have UTR's?

It also appears that TAGADA is creating single exon transcripts for multi-exon genes. Is this normal?

![image](https://github.com/FAANG/analysis-TAGADA/assets/11457166/46edd524-59cc-46c9-932b-00c15e99b1f7)

**Comment by sdjebali** [comment]
Hi Geoffrey,

I had a look at your files and indeed it seems that none of the novel transcripts exactly correspond to a transcript in the reference annotation, which makes the program crash. In fact we never observed that so I am wondering whether the previous steps went fine.

Maybe you could also share with me the directory that corresponds to the TMERGE_coalesce_transcripts process ?

Cheers,

**Comment by G-Thomson** [comment]
Hi Sarah

Thanks for looking into this. I have uploaded the TMERGE_coalesce_transcripts process into the same Google Drive directory.

Cheers

Geoffrey

**Comment by sdjebali** [comment]
Hi Geoffrey

it might not be the only issue but your input gtf file is weird

it seems that transcript ids should start with TCONS and gene ids with XLOC while I am seeing some rows where you also have transcript id starting with XLOC

like this one
`Hap1Sc1	FormBio	exon	15824174	15824266	.	+	.	gene_id "XLOC_000562"; transcript_id "XLOC_000562"; ID "exon-4220"; Parent "TCONS_00000466"; previous_transcript_id "TCONS_00000466.exon1";`

are you sure there was no issue when converting from gff3 to gtf format ? do you want me to try it ?

Cheers,

**Comment by G-Thomson** [comment]
Hi Sarah

Yes. It looks like these are exons from annotated tRNA and pseudogenes which I thought I had filtered out prior to conversion. I neglected to notice that tRNAs in gff3 have exons as well as gene, tRNA and RNA features.

I converted the files using the AGAT `agat_convert_sp_gff2gtf.pl --gtf_version 2.2` script.

I will try again and see if that makes a difference

Cheers

Geoffrey

**Comment by G-Thomson** [comment]
Hi Sarah

I re tried the pipeline with the re filtered GTF file (attached) and got the same TAGADA_control_annotation error again.
[OverlapsClassesACE_sorted.zip](https://github.com/FAANG/analysis-TAGADA/files/15214444/OverlapsClassesACE_sorted.zip)

```
ERROR ~ Error executing process > 'TAGADA_control_annotation (1)'

Caused by:
  Process `TAGADA_control_annotation (1)` terminated with an error exit status (2)
```


```
cat tmp_TAGADAWorkdir_try2/1f/538ce525d270e6a27fe05c63396804/detected_transcripts_genes_numbers.tsv 
Element	ref_nb	ref_in_file_nb	ref_in_file_pcent	ref_det_nb	ref_det_pcent	nov_nb	nov_det_nb	nov_det_pcent
transcript	58397	0	0	0	0	415023	315365	75.9874
gene	57954	0	0	0	0	112801	73757	65.3868
```

Any ideas?

**Comment by sdjebali** [comment]
OK

all depends if you are in a hurry or not, because I cannot investigate right now but I suspect there is a conflict between the field transcript_id and the field previous_transcript_id

do you mind making an initial ref gff file
- only with exon rows
- only with gene_id and transcript_id in the 9th field

and rerunning ?

there seems to be a problem at the TMERGE_coalesce_transcripts step, with the tmerge program, which writes in the contains field what is in the previous_transcript_id field (eg TCONS_00054330.exon1) instead of what is in the transcript_id field (eg TCONS_00054330) and this is why the downstream summary stats programs do not see any initial transcript in your novel annotation (TCONS_00054330.exon1 is not the id of an initial transcript)

**Comment by G-Thomson** [comment]
Hi Sarah

I tried that (see attached GTF file). 

[OverlapsClassesACE_sorted_justExons.zip](https://github.com/FAANG/analysis-TAGADA/files/15223707/OverlapsClassesACE_sorted_justExons.zip)

Unfortunately I got the same error. 

```
[56/380ab0] process > SAMTOOLS_sort_reads (28)       [100%] 40 of 40 ✔
[-        ] process > TRIMGALORE_trim_adapters       -
[-        ] process > FASTQC_control_reads           -
[-        ] process > STAR_index_genome              -
[-        ] process > STAR_align_reads               -
[6f/7d2d3a] process > SAMTOOLS_control_flags (39)    [100%] 40 of 40 ✔
[a4/f219af] process > SAMTOOLS_control_alignments... [100%] 40 of 40 ✔
[22/27e02b] process > SAMTOOLS_control_contigs (40)  [100%] 40 of 40 ✔
[8e/c9426a] process > TAGADA_estimate_reads (40)     [100%] 40 of 40 ✔
[48/01a95a] process > BEDTOOLS_compute_coverage (38) [100%] 40 of 40 ✔
[24/c3237a] process > MERGE_READS:SAMTOOLS_merge_... [100%] 15 of 15 ✔
[-        ] process > MERGE_READS:SAMTOOLS_merge_... -
[b6/6872ec] process > STRINGTIE_assemble_transcri... [100%] 15 of 15 ✔
[29/83c045] process > TAGADA_filter_transcripts      [100%] 1 of 1 ✔
[2a/e4f21c] process > TMERGE_coalesce_transcripts... [100%] 1 of 1 ✔
[-        ] process > FEELNC_classify_transcripts... -
[3d/6b58ae] process > STRINGTIE_quantify_expressi... [100%] 80 of 80 ✔
[56/57740b] process > TAGADA_format_quantificatio... [100%] 8 of 8 ✔
[51/ff6529] process > TAGADA_cluster_expression (1)  [100%] 1 of 1 ✔
[-        ] process > TAGADA_control_expression (1)  -
[97/6554a9] process > TAGADA_control_annotation (1)  [100%] 1 of 1, failed: 1 ✘
[c7/6fd430] process > FEATURECOUNTS_control_exons... [100%] 1 of 1
[-        ] process > MULTIQC_generate_report        -
ERROR ~ Error executing process > 'TAGADA_control_annotation (1)'

Caused by:
  Process `TAGADA_control_annotation (1)` terminated with an error exit status (2)
```

```
cat tmp_TAGADAWorkdir_try3/97/6554a90f35f9c05225ac245250b38b/detected_transcripts_genes_numbers.tsv 
Element	ref_nb	ref_in_file_nb	ref_in_file_pcent	ref_det_nb	ref_det_pcent	nov_nb	nov_det_nb	nov_det_pcent
transcript	58397	0	0	0	0	163348	146719	89.8199
gene	57954	0	0	0	0	67416	56090	83.1998
```

**Comment by sdjebali** [comment]
then it must come from something else than the previous run

could you please share the temporary directory of the `TMERGE_coalesce_transcripts` and of the `TAGADA_control_annotation` processes ? you can erase the previous ones.

sorry about that

**Comment by G-Thomson** [comment]
Hi Sarah

I have uploaded the `TMERGE_coalesce_transcripts` and `TAGADA_control_annotation` processes files from my last run. I also put the GTF file there too.

**Comment by sdjebali** [comment]
Hi Geoffrey

now I know what is happening. In fact the `control_annotation` step needs a reference gtf file with transcript rows (I also forgot about it!).

If you use  [this  reference gtf file](https://genoweb.toulouse.inrae.fr/~sdjebali/tagada/OverlapsClassesACE_sorted.gtf) as input to tagada it should work

sorry about that, we will add this constraint to the readme file

And let me know if you still have problems? 

In any case I suppose that you have all the quantification and novel annotation files that you need, this problem only affects the multiqc report ?

Best,

**Comment by G-Thomson** [comment]
Hi Sarah

It works! Thank you for your help. It is much appreciated.

For reference I found that I did get another error but I solved it by adding a `gene_id` field to each of the transcript rows of the GTF file.

Then it ran perfectly.
```
ERROR ~ Error executing process > 'FEELNC_classify_transcripts (1)'

Caused by:
  Process `FEELNC_classify_transcripts (1)` terminated with an error exit status (255)
```

```
  [Hap2Sc8	FormBio	transcript	27154300	27155554	.	+	.	transcript_id "TCONS_00086070";] does not contain 'gene_id' attribute...
```

Thnak-you!

**Comment by sdjebali** [comment]
Hi Geoffrey

I am happy that it finally worked for you, and sorry for the last error

this thread will certainly be useful to other users as well, so thanks for reaching out.

Best,
